{
 "title": "Blockscan Container Metrics",
 "tags": [
  "blockscan",
  "infra"
 ],
 "time": { "to": "now", "from": "now-15m" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": "blockscan" },
   {
    "name": "replica",
    "query": "label_values(docker_container_mem_usage{job=\"telegraf\",container_name=~\"blockscan-replica(1|2)\"}, container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (%) by replica",
   "type": "timeseries",
   "gridPos": { "y": 0, "h": 8, "w": 24, "x": 0 },
   "targets": [
    {
     "expr": "avg by (container_name) (rate(docker_container_cpu_usage_total{job=\"telegraf\", container_name=~\"blockscan-replica.*\", container_name=~\"$replica\"}[2m]) / 1e9 * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage (bytes) by replica",
   "type": "timeseries",
   "gridPos": { "y": 8, "h": 8, "w": 24, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (container_name) (docker_container_mem_usage{job=\"telegraf\", container_name=~\"blockscan-replica.*\", container_name=~\"$replica\"})"
    }
   ]
  },
  {
   "title": "Network IO Total (bytes/s) by replica",
   "type": "timeseries",
   "gridPos": { "y": 16, "h": 8, "w": 24, "x": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (container_name) ((rate(docker_container_net_rx_bytes{job=\"telegraf\", container_name=~\"blockscan-replica(1|2)\", container_name=~\"$replica\"}[1m]) + rate(docker_container_net_tx_bytes{job=\"telegraf\", container_name=~\"blockscan-replica(1|2)\", container_name=~\"$replica\"}[1m])))"
    }
   ]
  }
 ]
}